### ISSUE TITLE
is it right to scale microNormalLocal twice in getGGXDir?

### ISSUE THREAD

**Issue by StringHeart** [ChaosGroup/vraymtl_glsl#3]
in function 'vec3 getGGXDir()' in vratmtl_glsl microNormalLocal was scaled before get reflect dir. Then you pass this scaled microNormalLocal to 'getGGXContribution()', and in this function the microNormalLocal was scaled again to calculate BRDF.

is it right to scale this vector twice?

**Comment by asen1031** [comment]
The generated micro normal is isotropic. The first scale, before the reflection operator, transforms the normal to the stretched anisotropic surface. Before the BRDF evaluation we apply inverse scaling to retrieve the original isotropic micro normal (notice that "*"and "/" operations are swapped). To understand these calculations, please refer to the full derivation which is available in our paper, Sections 4.2 and 5.2 - https://docs.chaos.com/display/RESEARCH/Microsurface+Transformations.
